apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argo
  labels:
    argo.okmvp.internal/category: observer
spec:
  project: default
  source:
    repoURL: {{ .Values.repository }}
    targetRevision: {{ .Values.revision }}
    path: helm/observer/kibana/
    helm:
      parameters:
      - name:  kibana.ingress.hosts[0].host
        value: kibana.{{ .Values.domain }}
      valueFiles:
      - values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
