apiVersion: v2
name: istio
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  ## https://github.com/istio/istio/tree/1.11.2/manifests/charts/
  - name: base
    version: 1.11.2
    repository: file://./istio-1.11.2-charts/base
  - name: istio-discovery
    version: 1.11.2
    repository: file://./istio-1.11.2-charts/istio-control/istio-discovery
    alias: istiod
  - name: istio-ingress
    version: 1.11.2
    repository: file://./istio-1.11.2-charts/gateways/istio-ingress
  - name: istio-egress
    version: 1.11.2
    repository: file://./istio-1.11.2-charts/gateways/istio-egress