istiod:
  pilot:
    autoscaleEnabled: false
  global:
    jwtPolicy: first-party-jwt

istio-ingress:
  gateways:
    istio-ingressgateway:
      autoscaleEnabled: false
  global:
    jwtPolicy: first-party-jwt

istio-egress:
  gateways:
    istio-egressgateway:
      autoscaleEnabled: false
  global:
    jwtPolicy: first-party-jwt