apiVersion: v2
name: argo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://github.com/jetstack/cert-manager/tree/v1.3.1/deploy/charts/cert-manager
- name: cert-manager
  version: v1.3.1
  repository: https://charts.jetstack.io/
