apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo
  labels:
    argo.okmvp.internal/category: security
spec:
  project: default
  source:
    repoURL: {{ .Values.repository }}
    targetRevision: {{ .Values.revision }}
    path: helm/security/cert-manager
    helm:
      parameters:
      - name:  route53_access_key
        value: {{ index .Values.security "cert-manager" "route53_access_key" }}
      - name:  route53_secret_key_name
        value: {{ index .Values.security "cert-manager" "route53_secret_key_name" }}
      valueFiles:
      - values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
    - Validate=true
