apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: ghilbut@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
        - ghilbut.net
      dns01:
        route53:
          region: ap-northeast-2
          accessKeyID: {{ .Values.route53_access_key }}
          secretAccessKeySecretRef:
            name: {{ .Values.route53_secret_key_name }}
            key:  "secret_key"
    - selector:
        dnsZones:
        - ghilbut.com
      http01:
        ingress:
          class: istio
