apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: ghilbut@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - ghilbut.com
            - polykube.io
        http01:
          ingress:
            class: istio
      - selector:
          dnsZones:
            - ghilbut.net
            - polykube.in
            - polykube.net
        dns01:
          route53:
            region: {{ .Values.aws.region }}
            accessKeyID: {{ .Values.aws.access_key }}
            secretAccessKeySecretRef:
              name: aws-credential-secret
              key:  secret-access-key