apiVersion: v2
name: kiali
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

## https://github.com/kiali/helm-charts
dependencies:
  - name: kiali-operator
    version: 1.41.0
    repository: https://kiali.org/helm-charts/
    alias: operator
  - name: kiali-server
    version: 1.41.0
    repository: https://kiali.org/helm-charts/
    alias: server