################################################################
##
##  Elastic Stacks
##

##--------------------------------------------------------------
##  APM-Server

apm-server:
  fullnameOverride: apm
  apmConfig:
    apm-server.yml: |
      apm-server:
        host: "0.0.0.0:8200"
        rum:
          enabled: true
      queue: {}
      output.elasticsearch:
        hosts:
          - http://elasticsearch.elasticsearch.svc:9200
      monitoring:
        enabled: true
        elasticsearch:
          hosts:
            - http://elasticsearch.elasticsearch.svc:9200
  podAnnotations:
    #co.elastic.logs/enabled: "true"
    co.elastic.logs/enabled: "false"
    co.elastic.logs/format: json
    co.elastic.logs/json.add_error_key: "true"
    co.elastic.logs/json.keys_under_root: "true"
    co.elastic.logs/json.message_key: message
    co.elastic.logs/fileset.stdout: access
    co.elastic.logs/fileset.stderr: error
    co.elastic.logs/exclude_lines: "request ok"
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: docker-desktop


##--------------------------------------------------------------
##  Filebeat

filebeat:
  fullnameOverride: filebeat
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
        - type: kubernetes
          hints.enabled: true
      output.elasticsearch:
        hosts:
        - http://elasticsearch.elasticsearch.svc:9200
      monitoring:
        enabled: true
        elasticsearch:
          hosts:
          - http://elasticsearch.elasticsearch.svc:9200


##--------------------------------------------------------------
##  Metricbeat

metricbeat:
  fullnameOverride: metricbeat
  daemonset:
    metricbeatConfig:
      metricbeat.yml: |
        metricbeat.modules:
          - module: kubernetes
            metricsets:
              - container
              - node
              - pod
              - system
              - volume
            period: 10s
            host: "${NODE_NAME}"
            hosts: ["https://${NODE_NAME}:10250"]
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: "none"
            # If using Red Hat OpenShift remove ssl.verification_mode entry and
            # uncomment these settings:
            #ssl.certificate_authorities:
              #- /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            processors:
              - add_kubernetes_metadata: ~
          - module: kubernetes
            enabled: true
            metricsets:
              - event
          - module: system
            period: 10s
            metricsets:
              - cpu
              - load
              - memory
              - network
              - process
              - process_summary
            processes: ['.*']
            process.include_top_n:
              by_cpu: 5
              by_memory: 5
          - module: system
            period: 1m
            metricsets:
              - filesystem
              - fsstat
            processors:
              - drop_event.when.regexp:
                  system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
        output.elasticsearch:
          hosts:
            - http://elasticsearch.elasticsearch.svc:9200
        monitoring:
          enabled: true
          elasticsearch:
            hosts:
              - http://elasticsearch.elasticsearch.svc:9200
  deployment:
    metricbeatConfig:
      metricbeat.yml: |
        metricbeat.modules:
          - module: kubernetes
            enabled: true
            metricsets:
              - state_node
              - state_deployment
              - state_replicaset
              - state_pod
              - state_container
            period: 10s
            hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
        output.elasticsearch:
          hosts:
            - http://elasticsearch.elasticsearch.svc:9200
        monitoring:
          enabled: true
          elasticsearch:
            hosts:
              - http://elasticsearch.elasticsearch.svc:9200