version: "3.9"
services:
  galera-a:
    container_name: galera-a
    environment:
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      #- MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera-b:4567
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_NAME=exchange
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
      - MARIADB_GALERA_NODE_ADDRESS=galera-a
      - MARIADB_GALERA_MARIABACKUP_USER=backup
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backupw
      - MARIADB_ROOT_PASSWORD=rootpw
      - MARIADB_USER=user
      - MARIADB_PASSWORD=userpw
      - MARIADB_DATABASE=exchange
      - MARIADB_REPLICATION_USER=replication
      - MARIADB_REPLICATION_PASSWORD=replicationpw
    #healthcheck:
    #  test: [ 'CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh' ]
    #  interval: 15s
    #  timeout: 5s
    #  retries: 6
    image: bitnami/mariadb-galera:10.5.12
    networks:
      - galera
    ports:
      - 0.0.0.0:3306:3306
    restart: always
    #volumes:
    #  - ./galera-a-data:/bitnami/mariadb

  galera-b:
    container_name: galera-b
    depends_on:
      - galera-a
    environment:
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera-a:4567,0.0.0.0:4567
      - MARIADB_GALERA_CLUSTER_NAME=exchange
      - MARIADB_GALERA_NODE_ADDRESS=galera-b
      - MARIADB_GALERA_MARIABACKUP_USER=backup
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backupw
      - MARIADB_ROOT_PASSWORD=rootpw
      - MARIADB_REPLICATION_USER=replication
      - MARIADB_REPLICATION_PASSWORD=replicationpw
    #healthcheck:
    #  test: [ 'CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh' ]
    #  interval: 15s
    #  timeout: 5s
    #  retries: 6
    image: bitnami/mariadb-galera:10.5.12
    networks:
      - galera
    ports:
      - 0.0.0.0:13306:3306
    restart: always
    #volumes:
    #  - ./galera-b-data:/bitnami/mariadb

  #glb:
  #  build: ./glb/
  #  container_name: glb
  #  depends_on:
  #    - galera-a
  #    - galera-b
  #  environment:
  #    - DESTINATION_LIST="galera-a:4444 galera-b:4444"
  #  entrypoint:
  #    - glbd
  #    - --max_conn
  #    - "10"
  #    - --random
  #    - --threads
  #    - "2"
  #    - --verbose
  #    - 0.0.0.0:3306
  #  networks:
  #    - galera
  #  ports:
  #    - 0.0.0.0:3306:3306
  #  restart: always

  adminer:
    container_name: adminer
    depends_on:
      - galera-a
      - galera-b
    image: adminer:4.8.1
    networks:
      - galera
    ports:
      - 0.0.0.0:8080:8080
    restart: always

networks:
  galera:
    driver: bridge
    name: galera
