cd:
  kubeVersionOverride: 1.18

  dex:
    enabled: false

  server:
    extraArgs:
    - --insecure
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - ""
      paths:
      - "/"
    config:
      url: ""
      repositories: |
        - url: https://github.com/ghilbut/docker-desktop-k8s.git

  # Argo CD 3.6.x - Error: apiVersion 'v2' is not valid. The value must be "v1"
  #   - https://github.com/argoproj/argo-cd/issues/2383#issuecomment-582818583
  #   - https://github.com/argoproj/argo-helm/blob/argo-cd-3.6.6/charts/argo-cd/values.yaml#L931

