cd:
  kubeVersionOverride: 1.18

  dex:
    enabled: false

  server:
    extraArgs:
    - --insecure
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: istio
      hosts:
      - argo.ghilbut.net
      paths:
      - /*
    config:
      url: http://argo.ghilbut.net
      repositories: |
        - url: https://github.com/ghilbut/docker-desktop-k8s.git
