cd:
  kubeVersionOverride: 1.18

  dex:
    enabled: false

  server:
    extraArgs:
    - --insecure
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - ""
      paths:
      - "/"
    config:
      url: ""
      repositories: |
        - url: https://github.com/ghilbut/docker-desktop-k8s.git
