
domain: okmvp.internal

repository: https://github.com/okmvp/docker-desktop-k8s.git
revision:   main

security:
  cert-manager:
    route53_access_key: ""
    route53_secret_key_name: ""

network:
  ingress:
    type: istio
  metallb:
    enabled: true
    addresses: ""

data:
  elasticsearch:
    persistence:
      enabled: false
      dataDirSize: 4Gi
  kafka:
    enabled: false
    persistence:
      enabled: false
      zookeeper:
        dataDirSize: 1Gi
        dataLogDirSize: 4Gi
      kafka:
        dataDirSize: 4Gi
